version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abcd123@
    ports:
      - 1433:1433

  mongo:
    image: mongo:5.0.5
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
      
  migrations:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: ./Scripts/apply-migrations.sh

  blobstorage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: blobstorage
    ports:
      - "10000:10000"
      
